"""HyperFrames GitHub Registry 模板池(08-21 全量接入 373 个)。
来源: heygen-com/hyperframes GitHub
分类: 154 blocks + 219 components
文件: apps/frontend/assets/hyperframes-registry/blocks|components/<name>/<name>.html
"""

HYPERFRAMES_REGISTRY_TEMPLATES: tuple[str, ...] = (
    "hy:ai-chat-reveal",
    "hy:app-showcase",
    "hy:apple-money-count",
    "hy:bar-chart-race",
    "hy:beat-freeze-cut",
    "hy:blue-sweater-intro-video",
    "hy:camcorder-hud",
    "hy:camera-dolly-zoom",
    "hy:chatgpt-exchange",
    "hy:chromatic-radial-split",
    "hy:cinematic-zoom",
    "hy:claude-exchange",
    "hy:code-3d-extrude",
    "hy:code-diff",
    "hy:code-highlight",
    "hy:code-morph",
    "hy:code-particle-assemble",
    "hy:code-scroll",
    "hy:code-shader-dissolve",
    "hy:code-snippet-apple-terminal-basic",
    "hy:code-snippet-apple-terminal-clear-dark",
    "hy:code-snippet-apple-terminal-clear-light",
    "hy:code-snippet-apple-terminal-grass",
    "hy:code-snippet-apple-terminal-homebrew",
    "hy:code-snippet-apple-terminal-man-page",
    "hy:code-snippet-apple-terminal-novel",
    "hy:code-snippet-apple-terminal-ocean",
    "hy:code-snippet-apple-terminal-pro",
    "hy:code-snippet-apple-terminal-red-sands",
    "hy:code-snippet-apple-terminal-silver-aerogel",
    "hy:code-snippet-apple-terminal-solid-colors",
    "hy:code-snippet-dark-2026",
    "hy:code-snippet-dark-modern",
    "hy:code-snippet-dark-plus",
    "hy:code-snippet-flight",
    "hy:code-snippet-high-contrast-light",
    "hy:code-snippet-high-contrast",
    "hy:code-snippet-light-2026",
    "hy:code-snippet-light-modern",
    "hy:code-snippet-light-plus",
    "hy:code-snippet-monokai",
    "hy:code-snippet-solarized-light",
    "hy:code-snippet-visual-studio-dark",
    "hy:code-snippet-visual-studio-light",
    "hy:code-typing",
    "hy:cosmic-orb",
    "hy:cross-warp-morph",
    "hy:data-chart",
    "hy:domain-warp-dissolve",
    "hy:editorial-flash-overlay",
    "hy:flash-through-white",
    "hy:flowchart-vertical",
    "hy:flowchart",
    "hy:freeze-frame-dressing",
    "hy:gallery-tunnel",
    "hy:glitch",
    "hy:gravitational-lens",
    "hy:halftone-field",
    "hy:heygen-avatar-promo-card",
    "hy:hw-frame",
    "hy:hw-path-text",
    "hy:hw-pipeline",
    "hy:hw-scribble-transition",
    "hy:hw-text-cloud",
    "hy:hw-title",
    "hy:instagram-follow",
    "hy:ios26-liquid-glass",
    "hy:light-leak",
    "hy:liquid-glass-context-menu",
    "hy:liquid-glass-media-controls",
    "hy:liquid-glass-notification",
    "hy:liquid-glass-widgets",
    "hy:logo-outro",
    "hy:lower-third-bild",
    "hy:lt-accent-underline",
    "hy:lt-bold-block",
    "hy:lt-clean-bar",
    "hy:lt-color-block",
    "hy:lt-dark-card",
    "hy:lt-kicker-name",
    "hy:lt-mask-reveal",
    "hy:lt-neon-border",
    "hy:lt-side-rule",
    "hy:lt-soft-pill",
    "hy:lt-stack-bars",
    "hy:macos-notification",
    "hy:macos-tahoe-liquid-glass",
    "hy:message-thread-reveal",
    "hy:mk-background",
    "hy:mk-callout-highlight",
    "hy:mk-clone-wall-transition",
    "hy:mk-line-graph",
    "hy:mk-placeholder-grid",
    "hy:mk-progress-stat",
    "hy:mk-specs-list",
    "hy:news-ticker",
    "hy:north-korea-locked-down",
    "hy:notes-reveal",
    "hy:notification-cascade",
    "hy:nyc-paris-flight",
    "hy:organic-light-leak-overlay",
    "hy:oscilloscope-trace",
    "hy:rack-focus",
    "hy:reddit-post",
    "hy:ridged-burn",
    "hy:ripple-waves",
    "hy:sdf-iris",
    "hy:share-sheet-carousel",
    "hy:slack-notification-ad",
    "hy:spain-map",
    "hy:spiral-galaxy",
    "hy:split-flap-board",
    "hy:spotify-card",
    "hy:swirl-vortex",
    "hy:thermal-distortion",
    "hy:thread-message-stack",
    "hy:tiktok-follow",
    "hy:transitions-3d",
    "hy:transitions-blur",
    "hy:transitions-cover",
    "hy:transitions-destruction",
    "hy:transitions-dissolve",
    "hy:transitions-distortion",
    "hy:transitions-grid",
    "hy:transitions-light",
    "hy:transitions-mechanical",
    "hy:transitions-other",
    "hy:transitions-push",
    "hy:transitions-radial",
    "hy:transitions-scale",
    "hy:ui-3d-reveal",
    "hy:us-map-bubble",
    "hy:us-map-flow",
    "hy:us-map-hex",
    "hy:us-map",
    "hy:vfx-anamorphic-flare",
    "hy:vfx-iphone-device",
    "hy:vfx-liquid-background",
    "hy:vfx-liquid-glass",
    "hy:vfx-magnetic",
    "hy:vfx-portal",
    "hy:vfx-shatter",
    "hy:vfx-text-cursor",
    "hy:vpn-youtube-spot",
    "hy:weight-wave",
    "hy:whip-pan",
    "hy:world-map",
    "hy:x-post",
    "hy:yt-comment-card",
    "hy:yt-lcd-background",
    "hy:yt-logo-intro",
    "hy:yt-lower-third",
    "hy:yt-prism-title",
    "hy:yt-vertical-fill",
    "hy:animated-bar-chart",
    "hy:arc-motion-path",
    "hy:ascii-render-pass",
    "hy:ascii-trail-reveal",
    "hy:aurora-drift",
    "hy:avatar-cloud",
    "hy:avatar-group-hover",
    "hy:badge-pop",
    "hy:beat-accent",
    "hy:beat-pulse-background",
    "hy:beat-timeline",
    "hy:before-after-wipe",
    "hy:blur-in",
    "hy:blur-out-up",
    "hy:bottom-up-letters",
    "hy:browser-device-stage",
    "hy:camera-rig-depth-stack",
    "hy:camera-scan-gate",
    "hy:camera-shake",
    "hy:caption-blend-difference",
    "hy:caption-camera-follow",
    "hy:caption-clip-wipe",
    "hy:caption-editorial-emphasis",
    "hy:caption-emoji-pop",
    "hy:caption-glitch-rgb",
    "hy:caption-gradient-fill",
    "hy:caption-highlight",
    "hy:caption-kinetic-slam",
    "hy:caption-matrix-decode",
    "hy:caption-neon-accent",
    "hy:caption-neon-glow",
    "hy:caption-parallax-layers",
    "hy:caption-particle-burst",
    "hy:caption-pill-karaoke",
    "hy:caption-texture",
    "hy:caption-weight-shift",
    "hy:card-resize",
    "hy:char-slam-explode",
    "hy:chart-story",
    "hy:chat-message",
    "hy:chat-thread",
    "hy:checkout-flow",
    "hy:chromatic-aberration-wipe",
    "hy:code-terminal-run",
    "hy:comparison-split",
    "hy:confetti",
    "hy:conic-progress-ring",
    "hy:constellation-hub",
    "hy:count-up",
    "hy:cta-close",
    "hy:cta-lockup",
    "hy:cursor-glyph-trail",
    "hy:cut-the-curve",
    "hy:decline-chart",
    "hy:device-frame-stage",
    "hy:directional-wipe",
    "hy:drift-hold",
    "hy:dynamic-grid",
    "hy:echo-trail",
    "hy:facet-morph",
    "hy:fade-through",
    "hy:focus-blur-resolve",
    "hy:focus-rack",
    "hy:focus-swap",
    "hy:gesture-tap",
    "hy:gloss-sweep",
    "hy:grade-split-reveal",
    "hy:grain-field",
    "hy:grain-overlay",
    "hy:grid-card-assemble",
    "hy:grid-pixelate-wipe",
    "hy:halftone-dissolve",
    "hy:headline-slam",
    "hy:hw-arrow",
    "hy:hw-boil",
    "hy:hw-box-label",
    "hy:hw-callout-circle",
    "hy:hw-underline",
    "hy:icon-morph-beat",
    "hy:icon-swap",
    "hy:ink-bleed-reveal",
    "hy:inline-highlight",
    "hy:input-feedback",
    "hy:iris-reveal",
    "hy:keyframe-scrub-stack",
    "hy:kinetic-type-swap",
    "hy:light-sweep-pass",
    "hy:line-by-line-slide",
    "hy:line-swap",
    "hy:locked-nucleus-orbit",
    "hy:logo-brand-close",
    "hy:logo-sting",
    "hy:logo-wall",
    "hy:marker-checklist-card",
    "hy:marker-highlight",
    "hy:match-cut",
    "hy:matrix-decode",
    "hy:menu-morph",
    "hy:mesh-gradient-bg",
    "hy:micro-transitions",
    "hy:mk-emphasis-type",
    "hy:mk-usage-arc",
    "hy:modal-morph",
    "hy:morph-swap",
    "hy:morph-text",
    "hy:motion-blur",
    "hy:multi-device-splay",
    "hy:multiplayer-cursors",
    "hy:native-notification-pop",
    "hy:notes-typing",
    "hy:notification-pileup",
    "hy:notification-stack",
    "hy:number-pop-in",
    "hy:number-wheel",
    "hy:offset-path-traveler",
    "hy:onboarding-stepper-flow",
    "hy:ordered-dither-pass",
    "hy:outline-draw",
    "hy:oversized-cursor",
    "hy:overwhelm-surround",
    "hy:page-slide",
    "hy:pan-stations",
    "hy:panel-reveal",
    "hy:parallax-device-dive",
    "hy:parallax-unzoom",
    "hy:parallax-zoom",
    "hy:particle-image-reveal",
    "hy:particle-text-dissolve",
    "hy:per-word-crossfade",
    "hy:per-word-rise",
    "hy:perspective-marquee",
    "hy:physical-exit",
    "hy:press-ripple",
    "hy:pull-back-reveal",
    "hy:pull-to-refresh",
    "hy:push-in",
    "hy:radial-surround",
    "hy:rgb-glitch-text",
    "hy:rubber-band-bumper",
    "hy:scan-band",
    "hy:scramble-reveal",
    "hy:screen-flow-carousel",
    "hy:scroll-camera-story",
    "hy:scroll-feed",
    "hy:segmentation-flood",
    "hy:separator",
    "hy:settings-toggle-flow",
    "hy:shared-axis-y",
    "hy:shared-axis-z",
    "hy:sheet-spring-up",
    "hy:shimmer-sweep",
    "hy:signup-flow",
    "hy:simulated-cursor",
    "hy:skeleton-reveal",
    "hy:slit-scan-reveal",
    "hy:slot-machine-roll",
    "hy:social-proof-card",
    "hy:soft-blob-touch",
    "hy:soft-blur-in",
    "hy:split-tilt-cards",
    "hy:spotlight-card",
    "hy:spring-pop",
    "hy:spring-stack-shuffle",
    "hy:stagger-cascade",
    "hy:stagger-lattice",
    "hy:staggered-fade-up",
    "hy:star-rating-fill",
    "hy:state-chip-rail",
    "hy:sticky-mock-swap",
    "hy:stitched-text-draw",
    "hy:stop-motion-cadence",
    "hy:store-badge-lockup",
    "hy:streaming-text",
    "hy:strikethrough-replace",
    "hy:success-check",
    "hy:svg-line-draw-loader",
    "hy:svg-mask-reveal",
    "hy:svg-stroke-trace",
    "hy:swipe-rail",
    "hy:tabs-slide-indicator",
    "hy:telemetry-hud",
    "hy:terminal-simulator",
    "hy:testimonial-card",
    "hy:testimonial-proof-card",
    "hy:text-shimmer",
    "hy:text-stagger",
    "hy:text-state-swap",
    "hy:texture-mask-text",
    "hy:three-orbiting-cards",
    "hy:ticker-takeover",
    "hy:tilt-card",
    "hy:titlecard-calm",
    "hy:titlecard-lockup",
    "hy:toggle-flip",
    "hy:top-down-letters",
    "hy:touch-indicator",
    "hy:tracing-beam",
    "hy:tracking-in",
    "hy:trust-strip",
    "hy:type-match-cut",
    "hy:typed-prompt",
    "hy:typewriter",
    "hy:typing-indicator",
    "hy:ui-focus-zoom",
    "hy:variable-axis-type",
    "hy:variable-font-flex",
    "hy:vector-editor-rig",
    "hy:velocity-throw-snap",
    "hy:vignette",
    "hy:vox-annotate",
    "hy:whip-pan-cut",
    "hy:whiteboard-ink",
    "hy:wordmark-tiles",
    "hy:x-follow-card",
    "hy:yt-camera-move",
    "hy:yt-circle-pointer",
    "hy:yt-feather-highlight",
    "hy:yt-screen-warp",
    "hy:zoom-through-transition",
)

_TAG_TO_TEMPLATES: dict[str, list[str]] = {
    "3d": [
        "hy:app-showcase",
        "hy:camera-dolly-zoom",
        "hy:caption-parallax-layers",
        "hy:code-3d-extrude",
        "hy:cosmic-orb",
        "hy:gallery-tunnel",
        "hy:ios26-liquid-glass",
        "hy:macos-tahoe-liquid-glass",
        "hy:ui-3d-reveal",
        "hy:vfx-iphone-device",
    ],
    "accent": [
        "hy:caption-neon-accent",
    ],
    "actor": [
        "hy:oversized-cursor",
    ],
    "ad-template": [
        "hy:ai-chat-reveal",
        "hy:chatgpt-exchange",
        "hy:claude-exchange",
        "hy:heygen-avatar-promo-card",
        "hy:message-thread-reveal",
        "hy:notes-reveal",
        "hy:notification-cascade",
        "hy:share-sheet-carousel",
        "hy:slack-notification-ad",
    ],
    "advanced-motion": [
        "hy:camera-rig-depth-stack",
        "hy:keyframe-scrub-stack",
        "hy:stagger-lattice",
        "hy:svg-line-draw-loader",
    ],
    "agitate": [
        "hy:notification-pileup",
        "hy:overwhelm-surround",
        "hy:pan-stations",
    ],
    "agitation": [
        "hy:scroll-feed",
    ],
    "ai": [
        "hy:ai-chat-reveal",
        "hy:blue-sweater-intro-video",
        "hy:chatgpt-exchange",
        "hy:claude-exchange",
        "hy:segmentation-flood",
        "hy:streaming-text",
    ],
    "ambient": [
        "hy:aurora-drift",
        "hy:drift-hold",
        "hy:grain-field",
    ],
    "animation": [
        "hy:morph-text",
        "hy:motion-blur",
    ],
    "anime-inspired": [
        "hy:keyframe-scrub-stack",
        "hy:stagger-lattice",
        "hy:svg-line-draw-loader",
    ],
    "annotation": [
        "hy:hw-arrow",
        "hy:hw-boil",
        "hy:hw-box-label",
        "hy:hw-callout-circle",
        "hy:hw-underline",
        "hy:north-korea-locked-down",
        "hy:vox-annotate",
        "hy:yt-circle-pointer",
    ],
    "app": [
        "hy:app-showcase",
        "hy:vpn-youtube-spot",
    ],
    "app-chrome": [
        "hy:vector-editor-rig",
    ],
    "apple": [
        "hy:code-snippet-apple-terminal-basic",
        "hy:code-snippet-apple-terminal-clear-dark",
        "hy:code-snippet-apple-terminal-clear-light",
        "hy:code-snippet-apple-terminal-grass",
        "hy:code-snippet-apple-terminal-homebrew",
        "hy:code-snippet-apple-terminal-man-page",
        "hy:code-snippet-apple-terminal-novel",
        "hy:code-snippet-apple-terminal-ocean",
        "hy:code-snippet-apple-terminal-pro",
        "hy:code-snippet-apple-terminal-red-sands",
        "hy:code-snippet-apple-terminal-silver-aerogel",
        "hy:code-snippet-apple-terminal-solid-colors",
    ],
    "apple-terminal": [
        "hy:code-snippet-apple-terminal-basic",
        "hy:code-snippet-apple-terminal-clear-dark",
        "hy:code-snippet-apple-terminal-clear-light",
        "hy:code-snippet-apple-terminal-grass",
        "hy:code-snippet-apple-terminal-homebrew",
        "hy:code-snippet-apple-terminal-man-page",
        "hy:code-snippet-apple-terminal-novel",
        "hy:code-snippet-apple-terminal-ocean",
        "hy:code-snippet-apple-terminal-pro",
        "hy:code-snippet-apple-terminal-red-sands",
        "hy:code-snippet-apple-terminal-silver-aerogel",
        "hy:code-snippet-apple-terminal-solid-colors",
    ],
    "arcs": [
        "hy:us-map-flow",
    ],
    "arrow": [
        "hy:hw-arrow",
    ],
    "ascii": [
        "hy:ascii-render-pass",
        "hy:ascii-trail-reveal",
    ],
    "ask": [
        "hy:cta-close",
        "hy:cta-lockup",
        "hy:store-badge-lockup",
    ],
    "assemble": [
        "hy:grid-card-assemble",
    ],
    "attention": [
        "hy:focus-swap",
        "hy:tracing-beam",
    ],
    "aurora": [
        "hy:aurora-drift",
    ],
    "auto-rotate": [
        "hy:offset-path-traveler",
    ],
    "avatar": [
        "hy:avatar-group-hover",
        "hy:heygen-avatar-promo-card",
    ],
    "avatars": [
        "hy:avatar-cloud",
    ],
    "axis": [
        "hy:variable-axis-type",
    ],
    "background": [
        "hy:aurora-drift",
        "hy:beat-pulse-background",
        "hy:cosmic-orb",
        "hy:dynamic-grid",
        "hy:gallery-tunnel",
        "hy:grain-field",
        "hy:halftone-field",
        "hy:mk-background",
        "hy:spiral-galaxy",
        "hy:vfx-anamorphic-flare",
        "hy:vfx-liquid-background",
        "hy:yt-lcd-background",
    ],
    "badge": [
        "hy:badge-pop",
        "hy:gloss-sweep",
    ],
    "bars": [
        "hy:chart-story",
    ],
    "beam": [
        "hy:tracing-beam",
    ],
    "beat": [
        "hy:beat-pulse-background",
        "hy:line-swap",
    ],
    "beat-driven": [
        "hy:beat-freeze-cut",
    ],
    "before-after": [
        "hy:before-after-wipe",
        "hy:comparison-split",
    ],
    "bezier": [
        "hy:vector-editor-rig",
    ],
    "blend-mode": [
        "hy:caption-blend-difference",
    ],
    "blob": [
        "hy:soft-blob-touch",
    ],
    "blur": [
        "hy:focus-swap",
        "hy:soft-blur-in",
    ],
    "blur-in": [
        "hy:blur-in",
    ],
    "boil": [
        "hy:stop-motion-cadence",
    ],
    "bold": [
        "hy:lt-bold-block",
        "hy:lt-color-block",
        "hy:lt-kicker-name",
        "hy:lt-mask-reveal",
        "hy:lt-stack-bars",
    ],
    "book-open": [
        "hy:split-tilt-cards",
    ],
    "border": [
        "hy:outline-draw",
    ],
    "brand": [
        "hy:logo-brand-close",
        "hy:logo-sting",
    ],
    "branding": [
        "hy:logo-outro",
    ],
    "breather": [
        "hy:titlecard-lockup",
    ],
    "bridge": [
        "hy:beat-timeline",
        "hy:cut-the-curve",
        "hy:iris-reveal",
        "hy:whip-pan-cut",
    ],
    "broadcast": [
        "hy:lower-third-bild",
    ],
    "browser": [
        "hy:browser-device-stage",
    ],
    "bubble": [
        "hy:us-map-bubble",
    ],
    "burst": [
        "hy:beat-accent",
        "hy:caption-particle-burst",
    ],
    "callout": [
        "hy:hw-callout-circle",
    ],
    "calm": [
        "hy:titlecard-calm",
    ],
    "camcorder": [
        "hy:camcorder-hud",
    ],
    "camera": [
        "hy:camcorder-hud",
        "hy:camera-dolly-zoom",
        "hy:camera-scan-gate",
        "hy:camera-shake",
        "hy:caption-camera-follow",
        "hy:drift-hold",
        "hy:focus-rack",
        "hy:pan-stations",
        "hy:parallax-device-dive",
        "hy:pull-back-reveal",
        "hy:push-in",
        "hy:rack-focus",
        "hy:scroll-camera-story",
        "hy:ui-focus-zoom",
        "hy:yt-camera-move",
    ],
    "canvas": [
        "hy:particle-image-reveal",
        "hy:particle-text-dissolve",
        "hy:segmentation-flood",
        "hy:slit-scan-reveal",
        "hy:vfx-anamorphic-flare",
    ],
    "caption": [
        "hy:inline-highlight",
    ],
    "caption-style": [
        "hy:caption-camera-follow",
        "hy:caption-clip-wipe",
        "hy:caption-editorial-emphasis",
        "hy:caption-emoji-pop",
        "hy:caption-glitch-rgb",
        "hy:caption-gradient-fill",
        "hy:caption-highlight",
        "hy:caption-kinetic-slam",
        "hy:caption-matrix-decode",
        "hy:caption-neon-accent",
        "hy:caption-neon-glow",
        "hy:caption-parallax-layers",
        "hy:caption-particle-burst",
        "hy:caption-pill-karaoke",
        "hy:caption-texture",
        "hy:caption-weight-shift",
    ],
    "captions": [
        "hy:caption-camera-follow",
        "hy:caption-clip-wipe",
        "hy:caption-editorial-emphasis",
        "hy:caption-emoji-pop",
        "hy:caption-glitch-rgb",
        "hy:caption-gradient-fill",
        "hy:caption-highlight",
        "hy:caption-kinetic-slam",
        "hy:caption-matrix-decode",
        "hy:caption-neon-accent",
        "hy:caption-neon-glow",
        "hy:caption-parallax-layers",
        "hy:caption-particle-burst",
        "hy:caption-pill-karaoke",
        "hy:caption-texture",
        "hy:caption-weight-shift",
        "hy:mk-callout-highlight",
    ],
    "card": [
        "hy:card-resize",
        "hy:gloss-sweep",
        "hy:tilt-card",
    ],
    "cards": [
        "hy:swipe-rail",
    ],
    "carousel": [
        "hy:screen-flow-carousel",
    ],
    "celebration": [
        "hy:gloss-sweep",
    ],
    "chart": [
        "hy:bar-chart-race",
        "hy:chart-story",
        "hy:data-chart",
        "hy:decline-chart",
        "hy:mk-line-graph",
    ],
    "chat": [
        "hy:ai-chat-reveal",
        "hy:chat-message",
        "hy:chat-thread",
        "hy:chatgpt-exchange",
        "hy:claude-exchange",
        "hy:message-thread-reveal",
        "hy:streaming-text",
        "hy:typing-indicator",
    ],
    "check": [
        "hy:success-check",
    ],
    "checklist": [
        "hy:marker-checklist-card",
    ],
    "checkout": [
        "hy:checkout-flow",
    ],
    "chips": [
        "hy:state-chip-rail",
    ],
    "choropleth": [
        "hy:spain-map",
        "hy:us-map",
        "hy:world-map",
    ],
    "chromatic": [
        "hy:scan-band",
        "hy:vfx-text-cursor",
    ],
    "chrome": [
        "hy:browser-device-stage",
    ],
    "cinematic": [
        "hy:camera-dolly-zoom",
        "hy:camera-shake",
        "hy:rack-focus",
        "hy:vignette",
    ],
    "circle-reveal": [
        "hy:iris-reveal",
    ],
    "cities": [
        "hy:us-map-bubble",
    ],
    "clip-path": [
        "hy:caption-clip-wipe",
        "hy:iris-reveal",
    ],
    "close": [
        "hy:cta-close",
        "hy:logo-brand-close",
    ],
    "code": [
        "hy:code-3d-extrude",
        "hy:code-diff",
        "hy:code-highlight",
        "hy:code-morph",
        "hy:code-particle-assemble",
        "hy:code-scroll",
        "hy:code-shader-dissolve",
        "hy:code-snippet-apple-terminal-basic",
        "hy:code-snippet-apple-terminal-clear-dark",
        "hy:code-snippet-apple-terminal-clear-light",
        "hy:code-snippet-apple-terminal-grass",
        "hy:code-snippet-apple-terminal-homebrew",
        "hy:code-snippet-apple-terminal-man-page",
        "hy:code-snippet-apple-terminal-novel",
        "hy:code-snippet-apple-terminal-ocean",
        "hy:code-snippet-apple-terminal-pro",
        "hy:code-snippet-apple-terminal-red-sands",
        "hy:code-snippet-apple-terminal-silver-aerogel",
        "hy:code-snippet-apple-terminal-solid-colors",
        "hy:code-snippet-dark-2026",
        "hy:code-snippet-dark-modern",
        "hy:code-snippet-dark-plus",
        "hy:code-snippet-flight",
        "hy:code-snippet-high-contrast",
        "hy:code-snippet-high-contrast-light",
        "hy:code-snippet-light-2026",
        "hy:code-snippet-light-modern",
        "hy:code-snippet-light-plus",
        "hy:code-snippet-monokai",
        "hy:code-snippet-solarized-light",
        "hy:code-snippet-visual-studio-dark",
        "hy:code-snippet-visual-studio-light",
        "hy:code-typing",
    ],
    "code-animation": [
        "hy:code-3d-extrude",
        "hy:code-diff",
        "hy:code-highlight",
        "hy:code-morph",
        "hy:code-particle-assemble",
        "hy:code-scroll",
        "hy:code-shader-dissolve",
        "hy:code-snippet-flight",
        "hy:code-typing",
        "hy:terminal-simulator",
    ],
    "collaboration": [
        "hy:multiplayer-cursors",
    ],
    "color-grading": [
        "hy:grade-split-reveal",
    ],
    "colorful": [
        "hy:caption-gradient-fill",
    ],
    "comments": [
        "hy:yt-comment-card",
    ],
    "commerce": [
        "hy:checkout-flow",
    ],
    "community": [
        "hy:avatar-cloud",
    ],
    "compare": [
        "hy:before-after-wipe",
        "hy:comparison-split",
        "hy:grade-split-reveal",
        "hy:split-tilt-cards",
    ],
    "completion": [
        "hy:icon-morph-beat",
    ],
    "condense": [
        "hy:morph-swap",
    ],
    "conic-gradient": [
        "hy:conic-progress-ring",
    ],
    "connections": [
        "hy:us-map-flow",
    ],
    "connector": [
        "hy:constellation-hub",
    ],
    "continuity": [
        "hy:match-cut",
        "hy:type-match-cut",
    ],
    "contrast": [
        "hy:caption-blend-difference",
    ],
    "converge": [
        "hy:radial-surround",
    ],
    "conversation": [
        "hy:chat-thread",
        "hy:thread-message-stack",
    ],
    "countdown": [
        "hy:yt-circle-pointer",
    ],
    "counter": [
        "hy:count-up",
        "hy:number-wheel",
    ],
    "craft": [
        "hy:stitched-text-draw",
    ],
    "creator": [
        "hy:blue-sweater-intro-video",
        "hy:camcorder-hud",
        "hy:yt-camera-move",
        "hy:yt-comment-card",
        "hy:yt-lcd-background",
        "hy:yt-logo-intro",
        "hy:yt-prism-title",
    ],
    "cross-shelved": [
        "hy:pan-stations",
    ],
    "crossfade": [
        "hy:sticky-mock-swap",
    ],
    "cta": [
        "hy:cta-close",
        "hy:cta-lockup",
        "hy:social-proof-card",
        "hy:store-badge-lockup",
    ],
    "cursor": [
        "hy:cursor-glyph-trail",
        "hy:multiplayer-cursors",
        "hy:oversized-cursor",
        "hy:press-ripple",
        "hy:simulated-cursor",
        "hy:vfx-text-cursor",
    ],
    "cutout": [
        "hy:freeze-frame-dressing",
    ],
    "cyber": [
        "hy:caption-glitch-rgb",
    ],
    "dark": [
        "hy:lt-dark-card",
    ],
    "data": [
        "hy:animated-bar-chart",
        "hy:bar-chart-race",
        "hy:conic-progress-ring",
        "hy:data-chart",
        "hy:decline-chart",
        "hy:logo-wall",
        "hy:number-wheel",
        "hy:oscilloscope-trace",
        "hy:spain-map",
        "hy:star-rating-fill",
        "hy:us-map",
        "hy:us-map-bubble",
        "hy:us-map-flow",
        "hy:us-map-hex",
        "hy:world-map",
    ],
    "data-viz": [
        "hy:hw-pipeline",
        "hy:mk-line-graph",
        "hy:mk-progress-stat",
        "hy:mk-specs-list",
        "hy:mk-usage-arc",
    ],
    "decline": [
        "hy:decline-chart",
    ],
    "decode": [
        "hy:caption-matrix-decode",
    ],
    "demonstrate": [
        "hy:camera-scan-gate",
        "hy:conic-progress-ring",
        "hy:cursor-glyph-trail",
        "hy:cut-the-curve",
        "hy:echo-trail",
        "hy:focus-swap",
        "hy:pull-to-refresh",
        "hy:toggle-flip",
        "hy:vector-editor-rig",
    ],
    "departure-board": [
        "hy:split-flap-board",
    ],
    "depth": [
        "hy:camera-dolly-zoom",
        "hy:caption-parallax-layers",
        "hy:focus-rack",
        "hy:gallery-tunnel",
        "hy:rack-focus",
    ],
    "design-tool": [
        "hy:vector-editor-rig",
    ],
    "desktop": [
        "hy:multi-device-splay",
    ],
    "deterministic": [
        "hy:chart-story",
        "hy:code-terminal-run",
        "hy:count-up",
        "hy:cursor-glyph-trail",
        "hy:echo-trail",
        "hy:facet-morph",
        "hy:ink-bleed-reveal",
        "hy:light-sweep-pass",
        "hy:line-swap",
        "hy:locked-nucleus-orbit",
        "hy:marker-highlight",
        "hy:modal-morph",
        "hy:particle-image-reveal",
        "hy:particle-text-dissolve",
        "hy:scramble-reveal",
        "hy:segmentation-flood",
        "hy:slit-scan-reveal",
        "hy:stitched-text-draw",
        "hy:stop-motion-cadence",
        "hy:telemetry-hud",
        "hy:testimonial-proof-card",
        "hy:typed-prompt",
        "hy:variable-font-flex",
        "hy:vox-annotate",
    ],
    "developer": [
        "hy:code-3d-extrude",
        "hy:code-diff",
        "hy:code-highlight",
        "hy:code-morph",
        "hy:code-particle-assemble",
        "hy:code-scroll",
        "hy:code-shader-dissolve",
        "hy:code-snippet-apple-terminal-basic",
        "hy:code-snippet-apple-terminal-clear-dark",
        "hy:code-snippet-apple-terminal-clear-light",
        "hy:code-snippet-apple-terminal-grass",
        "hy:code-snippet-apple-terminal-homebrew",
        "hy:code-snippet-apple-terminal-man-page",
        "hy:code-snippet-apple-terminal-novel",
        "hy:code-snippet-apple-terminal-ocean",
        "hy:code-snippet-apple-terminal-pro",
        "hy:code-snippet-apple-terminal-red-sands",
        "hy:code-snippet-apple-terminal-silver-aerogel",
        "hy:code-snippet-apple-terminal-solid-colors",
        "hy:code-snippet-dark-2026",
        "hy:code-snippet-dark-modern",
        "hy:code-snippet-dark-plus",
        "hy:code-snippet-flight",
        "hy:code-snippet-high-contrast",
        "hy:code-snippet-high-contrast-light",
        "hy:code-snippet-light-2026",
        "hy:code-snippet-light-modern",
        "hy:code-snippet-light-plus",
        "hy:code-snippet-monokai",
        "hy:code-snippet-solarized-light",
        "hy:code-snippet-visual-studio-dark",
        "hy:code-snippet-visual-studio-light",
        "hy:code-typing",
    ],
    "device": [
        "hy:browser-device-stage",
        "hy:device-frame-stage",
        "hy:multi-device-splay",
        "hy:parallax-device-dive",
        "hy:vfx-iphone-device",
    ],
    "diagram": [
        "hy:flowchart",
        "hy:flowchart-vertical",
        "hy:hw-pipeline",
    ],
    "diff": [
        "hy:code-diff",
    ],
    "directional-cut": [
        "hy:cut-the-curve",
    ],
    "displacement": [
        "hy:vfx-liquid-background",
    ],
    "dissolve": [
        "hy:halftone-dissolve",
    ],
    "distortion": [
        "hy:scan-band",
    ],
    "dither": [
        "hy:ordered-dither-pass",
    ],
    "donut": [
        "hy:chart-story",
    ],
    "dots": [
        "hy:grain-field",
    ],
    "drift": [
        "hy:drift-hold",
    ],
    "drop": [
        "hy:physical-exit",
    ],
    "editorial": [
        "hy:caption-editorial-emphasis",
        "hy:editorial-flash-overlay",
    ],
    "effect": [
        "hy:camera-shake",
        "hy:caption-blend-difference",
        "hy:confetti",
        "hy:focus-swap",
        "hy:hw-boil",
        "hy:mesh-gradient-bg",
        "hy:motion-blur",
        "hy:shimmer-sweep",
        "hy:spotlight-card",
        "hy:svg-mask-reveal",
        "hy:texture-mask-text",
        "hy:vignette",
        "hy:yt-camera-move",
        "hy:yt-feather-highlight",
        "hy:yt-screen-warp",
    ],
    "effects": [
        "hy:avatar-cloud",
        "hy:beat-accent",
        "hy:caption-particle-burst",
        "hy:outline-draw",
        "hy:overwhelm-surround",
        "hy:scroll-feed",
        "hy:spring-pop",
        "hy:stagger-cascade",
    ],
    "emoji": [
        "hy:caption-emoji-pop",
    ],
    "emphasis": [
        "hy:caption-editorial-emphasis",
        "hy:marker-highlight",
        "hy:text-shimmer",
    ],
    "emphasize": [
        "hy:beat-accent",
        "hy:focus-rack",
        "hy:push-in",
        "hy:variable-axis-type",
    ],
    "end-card": [
        "hy:cta-close",
        "hy:cta-lockup",
        "hy:logo-brand-close",
        "hy:social-proof-card",
    ],
    "entrance": [
        "hy:stagger-cascade",
    ],
    "europe": [
        "hy:spain-map",
    ],
    "exhibit": [
        "hy:pan-stations",
        "hy:stagger-cascade",
        "hy:svg-mask-reveal",
    ],
    "exit": [
        "hy:headline-slam",
        "hy:physical-exit",
    ],
    "experiment": [
        "hy:ascii-render-pass",
        "hy:ink-bleed-reveal",
        "hy:modal-morph",
        "hy:ordered-dither-pass",
        "hy:particle-text-dissolve",
        "hy:segmentation-flood",
        "hy:slit-scan-reveal",
        "hy:stitched-text-draw",
        "hy:stop-motion-cadence",
        "hy:variable-font-flex",
    ],
    "fade": [
        "hy:fade-through",
    ],
    "feature-tour": [
        "hy:constellation-hub",
        "hy:grid-card-assemble",
        "hy:screen-flow-carousel",
        "hy:sticky-mock-swap",
        "hy:velocity-throw-snap",
    ],
    "features": [
        "hy:pan-stations",
    ],
    "feed": [
        "hy:scroll-feed",
    ],
    "feedback": [
        "hy:input-feedback",
    ],
    "fill": [
        "hy:star-rating-fill",
    ],
    "film": [
        "hy:grain-overlay",
        "hy:organic-light-leak-overlay",
    ],
    "finance": [
        "hy:apple-money-count",
    ],
    "flash": [
        "hy:editorial-flash-overlay",
    ],
    "flight": [
        "hy:code-snippet-flight",
    ],
    "flip": [
        "hy:modal-morph",
    ],
    "flow": [
        "hy:us-map-flow",
    ],
    "flowchart": [
        "hy:flowchart",
        "hy:flowchart-vertical",
    ],
    "focus": [
        "hy:focus-rack",
        "hy:focus-swap",
        "hy:push-in",
        "hy:ui-focus-zoom",
    ],
    "focus-rack": [
        "hy:focus-rack",
    ],
    "form": [
        "hy:signup-flow",
    ],
    "fractional": [
        "hy:star-rating-fill",
    ],
    "frame": [
        "hy:hw-frame",
    ],
    "freeze-frame": [
        "hy:beat-freeze-cut",
        "hy:freeze-frame-dressing",
    ],
    "gaming": [
        "hy:caption-neon-glow",
    ],
    "gauge": [
        "hy:mk-usage-arc",
    ],
    "geography": [
        "hy:spain-map",
        "hy:us-map",
        "hy:us-map-bubble",
        "hy:us-map-flow",
        "hy:us-map-hex",
        "hy:world-map",
    ],
    "gesture": [
        "hy:gesture-tap",
        "hy:pull-to-refresh",
        "hy:swipe-rail",
        "hy:touch-indicator",
    ],
    "ghosts": [
        "hy:echo-trail",
    ],
    "glitch": [
        "hy:caption-glitch-rgb",
    ],
    "gloss": [
        "hy:gloss-sweep",
    ],
    "glow": [
        "hy:caption-neon-accent",
        "hy:caption-neon-glow",
        "hy:lt-neon-border",
    ],
    "gltf": [
        "hy:ios26-liquid-glass",
        "hy:macos-tahoe-liquid-glass",
        "hy:vfx-iphone-device",
    ],
    "glyphs": [
        "hy:cursor-glyph-trail",
    ],
    "gooey": [
        "hy:ink-bleed-reveal",
        "hy:morph-text",
    ],
    "gpu": [
        "hy:code-particle-assemble",
    ],
    "grade": [
        "hy:grade-split-reveal",
    ],
    "gradient": [
        "hy:aurora-drift",
        "hy:caption-gradient-fill",
        "hy:mk-background",
    ],
    "grain": [
        "hy:grain-field",
        "hy:grain-overlay",
        "hy:soft-blob-touch",
    ],
    "graph": [
        "hy:mk-line-graph",
    ],
    "grid": [
        "hy:ascii-trail-reveal",
        "hy:dynamic-grid",
        "hy:grid-card-assemble",
        "hy:grid-pixelate-wipe",
        "hy:mk-placeholder-grid",
        "hy:parallax-unzoom",
        "hy:parallax-zoom",
        "hy:stagger-cascade",
    ],
    "gsap-plugin": [
        "hy:arc-motion-path",
    ],
    "halftone": [
        "hy:halftone-dissolve",
        "hy:halftone-field",
    ],
    "handheld": [
        "hy:camera-shake",
    ],
    "handwritten": [
        "hy:hw-arrow",
        "hy:hw-boil",
        "hy:hw-box-label",
        "hy:hw-callout-circle",
        "hy:hw-frame",
        "hy:hw-path-text",
        "hy:hw-pipeline",
        "hy:hw-scribble-transition",
        "hy:hw-text-cloud",
        "hy:hw-title",
        "hy:hw-underline",
        "hy:marker-checklist-card",
    ],
    "hard-cut": [
        "hy:match-cut",
    ],
    "headline": [
        "hy:headline-slam",
        "hy:ticker-takeover",
    ],
    "hero": [
        "hy:parallax-unzoom",
        "hy:parallax-zoom",
        "hy:spiral-galaxy",
    ],
    "hexgrid": [
        "hy:us-map-hex",
    ],
    "highlight": [
        "hy:caption-highlight",
        "hy:code-highlight",
        "hy:inline-highlight",
        "hy:shimmer-sweep",
        "hy:yt-feather-highlight",
    ],
    "hold": [
        "hy:drift-hold",
    ],
    "holdable": [
        "hy:before-after-wipe",
        "hy:comparison-split",
        "hy:device-frame-stage",
        "hy:morph-swap",
        "hy:push-in",
        "hy:split-tilt-cards",
    ],
    "hover": [
        "hy:avatar-group-hover",
    ],
    "html-in-canvas": [
        "hy:ios26-liquid-glass",
        "hy:liquid-glass-context-menu",
        "hy:liquid-glass-media-controls",
        "hy:liquid-glass-notification",
        "hy:liquid-glass-widgets",
        "hy:macos-tahoe-liquid-glass",
        "hy:vfx-iphone-device",
        "hy:vfx-liquid-background",
        "hy:vfx-liquid-glass",
        "hy:vfx-magnetic",
        "hy:vfx-portal",
        "hy:vfx-shatter",
        "hy:vfx-text-cursor",
    ],
    "hub": [
        "hy:constellation-hub",
    ],
    "hud": [
        "hy:camcorder-hud",
        "hy:segmentation-flood",
        "hy:telemetry-hud",
    ],
    "hyperframes-native": [
        "hy:arc-motion-path",
        "hy:camera-rig-depth-stack",
        "hy:keyframe-scrub-stack",
        "hy:stagger-lattice",
        "hy:svg-line-draw-loader",
        "hy:three-orbiting-cards",
    ],
    "icon": [
        "hy:icon-morph-beat",
        "hy:icon-swap",
    ],
    "impact": [
        "hy:beat-accent",
        "hy:char-slam-explode",
        "hy:headline-slam",
        "hy:logo-sting",
    ],
    "indicator": [
        "hy:tabs-slide-indicator",
    ],
    "input": [
        "hy:input-feedback",
    ],
    "instagram": [
        "hy:instagram-follow",
    ],
    "instrument": [
        "hy:oscilloscope-trace",
    ],
    "interaction": [
        "hy:camera-scan-gate",
        "hy:gesture-tap",
        "hy:oversized-cursor",
        "hy:pull-to-refresh",
        "hy:swipe-rail",
        "hy:toggle-flip",
    ],
    "interactive": [
        "hy:flowchart",
        "hy:flowchart-vertical",
    ],
    "interruptible-spring": [
        "hy:spring-stack-shuffle",
    ],
    "interview": [
        "hy:lt-accent-underline",
        "hy:lt-bold-block",
        "hy:lt-clean-bar",
        "hy:lt-color-block",
        "hy:lt-dark-card",
        "hy:lt-kicker-name",
        "hy:lt-mask-reveal",
        "hy:lt-side-rule",
        "hy:lt-soft-pill",
        "hy:lt-stack-bars",
    ],
    "intro": [
        "hy:ascii-trail-reveal",
        "hy:facet-morph",
        "hy:locked-nucleus-orbit",
        "hy:svg-stroke-trace",
        "hy:whiteboard-ink",
        "hy:yt-logo-intro",
    ],
    "intros-reveals": [
        "hy:particle-image-reveal",
    ],
    "inversion": [
        "hy:caption-blend-difference",
    ],
    "ios26": [
        "hy:ios26-liquid-glass",
    ],
    "iphone": [
        "hy:ios26-liquid-glass",
        "hy:vfx-iphone-device",
    ],
    "iris": [
        "hy:iris-reveal",
    ],
    "karaoke": [
        "hy:caption-pill-karaoke",
        "hy:mk-callout-highlight",
    ],
    "kinetic": [
        "hy:apple-money-count",
        "hy:caption-kinetic-slam",
        "hy:morph-text",
        "hy:north-korea-locked-down",
        "hy:split-flap-board",
    ],
    "kinetic-type": [
        "hy:kinetic-type-swap",
        "hy:variable-axis-type",
        "hy:weight-wave",
    ],
    "layout": [
        "hy:card-resize",
        "hy:grid-card-assemble",
        "hy:separator",
        "hy:split-tilt-cards",
    ],
    "letters": [
        "hy:bottom-up-letters",
    ],
    "light": [
        "hy:editorial-flash-overlay",
        "hy:light-sweep-pass",
    ],
    "light-leak": [
        "hy:organic-light-leak-overlay",
    ],
    "line": [
        "hy:chart-story",
    ],
    "line-draw": [
        "hy:svg-stroke-trace",
        "hy:whiteboard-ink",
    ],
    "liquid": [
        "hy:vfx-liquid-background",
    ],
    "liquid-glass-html-in-canvas": [
        "hy:ios26-liquid-glass",
        "hy:liquid-glass-context-menu",
        "hy:liquid-glass-media-controls",
        "hy:liquid-glass-notification",
        "hy:liquid-glass-widgets",
    ],
    "list": [
        "hy:grid-card-assemble",
        "hy:mk-specs-list",
    ],
    "lockup": [
        "hy:cta-lockup",
        "hy:locked-nucleus-orbit",
        "hy:titlecard-lockup",
    ],
    "logo": [
        "hy:logo-brand-close",
        "hy:logo-outro",
        "hy:logo-sting",
        "hy:yt-logo-intro",
    ],
    "logo-strip": [
        "hy:trust-strip",
    ],
    "logos": [
        "hy:logo-wall",
    ],
    "loop": [
        "hy:gallery-tunnel",
        "hy:lt-neon-border",
        "hy:multiplayer-cursors",
        "hy:notification-pileup",
        "hy:scroll-feed",
    ],
    "loopable": [
        "hy:aurora-drift",
        "hy:drift-hold",
        "hy:grain-field",
    ],
    "low-poly": [
        "hy:facet-morph",
    ],
    "lower-third": [
        "hy:lower-third-bild",
        "hy:lt-accent-underline",
        "hy:lt-bold-block",
        "hy:lt-clean-bar",
        "hy:lt-color-block",
        "hy:lt-dark-card",
        "hy:lt-kicker-name",
        "hy:lt-mask-reveal",
        "hy:lt-neon-border",
        "hy:lt-side-rule",
        "hy:lt-soft-pill",
        "hy:lt-stack-bars",
        "hy:news-ticker",
    ],
    "macbook": [
        "hy:vfx-iphone-device",
    ],
    "macos": [
        "hy:macos-tahoe-liquid-glass",
    ],
    "map": [
        "hy:north-korea-locked-down",
        "hy:nyc-paris-flight",
        "hy:spain-map",
        "hy:us-map",
        "hy:us-map-bubble",
        "hy:us-map-flow",
        "hy:us-map-hex",
        "hy:world-map",
    ],
    "marker": [
        "hy:marker-checklist-card",
        "hy:marker-highlight",
        "hy:vox-annotate",
    ],
    "mask": [
        "hy:caption-texture",
        "hy:outline-draw",
        "hy:svg-mask-reveal",
        "hy:texture-mask-text",
    ],
    "match-cut": [
        "hy:match-cut",
        "hy:type-match-cut",
    ],
    "material": [
        "hy:soft-blob-touch",
    ],
    "matrix": [
        "hy:caption-matrix-decode",
    ],
    "mechanical": [
        "hy:split-flap-board",
    ],
    "media": [
        "hy:grade-split-reveal",
        "hy:hw-frame",
        "hy:mk-placeholder-grid",
        "hy:yt-vertical-fill",
    ],
    "media-treatment-overlay": [
        "hy:camcorder-hud",
        "hy:editorial-flash-overlay",
        "hy:freeze-frame-dressing",
        "hy:organic-light-leak-overlay",
    ],
    "memory": [
        "hy:organic-light-leak-overlay",
    ],
    "menu": [
        "hy:menu-morph",
    ],
    "message": [
        "hy:chat-message",
    ],
    "messages": [
        "hy:thread-message-stack",
    ],
    "metric": [
        "hy:decline-chart",
    ],
    "microinteraction": [
        "hy:badge-pop",
        "hy:micro-transitions",
    ],
    "minimal": [
        "hy:caption-weight-shift",
        "hy:lt-accent-underline",
        "hy:lt-side-rule",
        "hy:lt-soft-pill",
        "hy:mk-background",
        "hy:mk-callout-highlight",
        "hy:mk-emphasis-type",
        "hy:mk-line-graph",
        "hy:mk-placeholder-grid",
        "hy:mk-progress-stat",
        "hy:mk-specs-list",
        "hy:mk-usage-arc",
    ],
    "mobile": [
        "hy:device-frame-stage",
        "hy:notification-pileup",
        "hy:pull-to-refresh",
        "hy:store-badge-lockup",
        "hy:touch-indicator",
    ],
    "mock": [
        "hy:sticky-mock-swap",
    ],
    "mock-ui": [
        "hy:ai-chat-reveal",
        "hy:chat-message",
        "hy:chat-thread",
        "hy:chatgpt-exchange",
        "hy:claude-exchange",
        "hy:message-thread-reveal",
        "hy:notes-reveal",
        "hy:notes-typing",
        "hy:notification-cascade",
        "hy:share-sheet-carousel",
        "hy:sheet-spring-up",
        "hy:slack-notification-ad",
        "hy:typing-indicator",
    ],
    "modal": [
        "hy:modal-morph",
    ],
    "momentum": [
        "hy:physical-exit",
    ],
    "morph": [
        "hy:code-morph",
        "hy:facet-morph",
        "hy:icon-morph-beat",
        "hy:menu-morph",
        "hy:morph-swap",
        "hy:morph-text",
    ],
    "motion-blur": [
        "hy:motion-blur",
        "hy:whip-pan-cut",
    ],
    "motion-primitive": [
        "hy:ascii-render-pass",
        "hy:ascii-trail-reveal",
        "hy:aurora-drift",
        "hy:beat-accent",
        "hy:beat-pulse-background",
        "hy:blur-out-up",
        "hy:bottom-up-letters",
        "hy:caption-camera-follow",
        "hy:char-slam-explode",
        "hy:chart-story",
        "hy:chat-thread",
        "hy:code-terminal-run",
        "hy:constellation-hub",
        "hy:count-up",
        "hy:cta-close",
        "hy:cta-lockup",
        "hy:cursor-glyph-trail",
        "hy:decline-chart",
        "hy:drift-hold",
        "hy:dynamic-grid",
        "hy:echo-trail",
        "hy:facet-morph",
        "hy:fade-through",
        "hy:focus-blur-resolve",
        "hy:focus-rack",
        "hy:gesture-tap",
        "hy:gloss-sweep",
        "hy:grade-split-reveal",
        "hy:grain-field",
        "hy:grid-card-assemble",
        "hy:halftone-dissolve",
        "hy:headline-slam",
        "hy:icon-morph-beat",
        "hy:ink-bleed-reveal",
        "hy:inline-highlight",
        "hy:kinetic-type-swap",
        "hy:light-sweep-pass",
        "hy:line-by-line-slide",
        "hy:line-swap",
        "hy:locked-nucleus-orbit",
        "hy:logo-brand-close",
        "hy:logo-sting",
        "hy:marker-checklist-card",
        "hy:marker-highlight",
        "hy:match-cut",
        "hy:matrix-decode",
        "hy:micro-transitions",
        "hy:modal-morph",
        "hy:multi-device-splay",
        "hy:native-notification-pop",
        "hy:notes-typing",
        "hy:notification-stack",
        "hy:number-wheel",
        "hy:offset-path-traveler",
        "hy:ordered-dither-pass",
        "hy:outline-draw",
        "hy:oversized-cursor",
        "hy:parallax-device-dive",
        "hy:particle-image-reveal",
        "hy:particle-text-dissolve",
        "hy:per-word-crossfade",
        "hy:per-word-rise",
        "hy:perspective-marquee",
        "hy:physical-exit",
        "hy:press-ripple",
        "hy:pull-back-reveal",
        "hy:push-in",
        "hy:radial-surround",
        "hy:rgb-glitch-text",
        "hy:rubber-band-bumper",
        "hy:scan-band",
        "hy:scramble-reveal",
        "hy:scroll-feed",
        "hy:segmentation-flood",
        "hy:shared-axis-y",
        "hy:shared-axis-z",
        "hy:simulated-cursor",
        "hy:slit-scan-reveal",
        "hy:slot-machine-roll",
        "hy:social-proof-card",
        "hy:soft-blob-touch",
        "hy:soft-blur-in",
        "hy:split-tilt-cards",
        "hy:spring-pop",
        "hy:spring-stack-shuffle",
        "hy:staggered-fade-up",
        "hy:state-chip-rail",
        "hy:sticky-mock-swap",
        "hy:stitched-text-draw",
        "hy:stop-motion-cadence",
        "hy:strikethrough-replace",
        "hy:svg-stroke-trace",
        "hy:swipe-rail",
        "hy:telemetry-hud",
        "hy:testimonial-proof-card",
        "hy:text-shimmer",
        "hy:ticker-takeover",
        "hy:titlecard-calm",
        "hy:titlecard-lockup",
        "hy:top-down-letters",
        "hy:touch-indicator",
        "hy:tracing-beam",
        "hy:tracking-in",
        "hy:trust-strip",
        "hy:type-match-cut",
        "hy:typed-prompt",
        "hy:typewriter",
        "hy:variable-font-flex",
        "hy:velocity-throw-snap",
        "hy:vox-annotate",
        "hy:whiteboard-ink",
    ],
    "motionpath": [
        "hy:arc-motion-path",
    ],
    "multiplayer": [
        "hy:multiplayer-cursors",
    ],
    "music": [
        "hy:beat-freeze-cut",
    ],
    "neon": [
        "hy:caption-neon-accent",
        "hy:caption-neon-glow",
    ],
    "network": [
        "hy:avatar-cloud",
    ],
    "news": [
        "hy:lower-third-bild",
        "hy:news-ticker",
    ],
    "nodes": [
        "hy:constellation-hub",
    ],
    "notes": [
        "hy:notes-reveal",
        "hy:notes-typing",
    ],
    "notification": [
        "hy:macos-notification",
        "hy:native-notification-pop",
        "hy:notification-cascade",
        "hy:notification-pileup",
        "hy:notification-stack",
        "hy:slack-notification-ad",
    ],
    "notifications": [
        "hy:ios26-liquid-glass",
        "hy:overwhelm-surround",
    ],
    "number": [
        "hy:count-up",
        "hy:number-pop-in",
        "hy:number-wheel",
    ],
    "onboarding": [
        "hy:onboarding-stepper-flow",
    ],
    "onion-skin": [
        "hy:echo-trail",
    ],
    "optical": [
        "hy:vfx-anamorphic-flare",
    ],
    "orbit": [
        "hy:locked-nucleus-orbit",
    ],
    "orchestration": [
        "hy:beat-timeline",
    ],
    "orient": [
        "hy:titlecard-calm",
        "hy:titlecard-lockup",
    ],
    "outline": [
        "hy:outline-draw",
    ],
    "outro": [
        "hy:logo-outro",
    ],
    "overlay": [
        "hy:camcorder-hud",
        "hy:editorial-flash-overlay",
        "hy:freeze-frame-dressing",
        "hy:grain-overlay",
        "hy:hw-arrow",
        "hy:hw-box-label",
        "hy:hw-callout-circle",
        "hy:hw-path-text",
        "hy:hw-pipeline",
        "hy:hw-text-cloud",
        "hy:hw-title",
        "hy:instagram-follow",
        "hy:light-sweep-pass",
        "hy:lower-third-bild",
        "hy:lt-accent-underline",
        "hy:lt-bold-block",
        "hy:lt-clean-bar",
        "hy:lt-color-block",
        "hy:lt-dark-card",
        "hy:lt-kicker-name",
        "hy:lt-mask-reveal",
        "hy:lt-side-rule",
        "hy:lt-soft-pill",
        "hy:lt-stack-bars",
        "hy:macos-notification",
        "hy:native-notification-pop",
        "hy:news-ticker",
        "hy:organic-light-leak-overlay",
        "hy:reddit-post",
        "hy:sheet-spring-up",
        "hy:spotify-card",
        "hy:tiktok-follow",
        "hy:typing-indicator",
        "hy:vignette",
        "hy:x-post",
        "hy:yt-circle-pointer",
        "hy:yt-comment-card",
        "hy:yt-feather-highlight",
        "hy:yt-lower-third",
        "hy:yt-screen-warp",
    ],
    "overload": [
        "hy:notification-pileup",
    ],
    "overshoot": [
        "hy:rubber-band-bumper",
        "hy:spring-pop",
    ],
    "overwhelm": [
        "hy:overwhelm-surround",
    ],
    "page": [
        "hy:page-slide",
    ],
    "pan": [
        "hy:pan-stations",
        "hy:ui-focus-zoom",
    ],
    "panel": [
        "hy:panel-reveal",
    ],
    "paper": [
        "hy:freeze-frame-dressing",
        "hy:marker-checklist-card",
    ],
    "parallax": [
        "hy:caption-parallax-layers",
        "hy:focus-rack",
        "hy:parallax-device-dive",
        "hy:parallax-unzoom",
        "hy:parallax-zoom",
        "hy:scroll-camera-story",
    ],
    "particles": [
        "hy:caption-particle-burst",
        "hy:code-particle-assemble",
        "hy:particle-image-reveal",
        "hy:particle-text-dissolve",
        "hy:spiral-galaxy",
    ],
    "path": [
        "hy:hw-path-text",
        "hy:offset-path-traveler",
        "hy:tracing-beam",
    ],
    "payoff": [
        "hy:gloss-sweep",
        "hy:press-ripple",
    ],
    "pen-tool": [
        "hy:vector-editor-rig",
    ],
    "phone": [
        "hy:browser-device-stage",
        "hy:multi-device-splay",
        "hy:parallax-device-dive",
    ],
    "physics": [
        "hy:motion-blur",
        "hy:spring-stack-shuffle",
        "hy:velocity-throw-snap",
    ],
    "pileup": [
        "hy:notification-pileup",
    ],
    "pill": [
        "hy:caption-pill-karaoke",
    ],
    "pixelate": [
        "hy:grid-pixelate-wipe",
    ],
    "placeholder": [
        "hy:mk-placeholder-grid",
        "hy:yt-vertical-fill",
    ],
    "podcast": [
        "hy:lt-accent-underline",
        "hy:lt-bold-block",
        "hy:lt-clean-bar",
        "hy:lt-color-block",
        "hy:lt-dark-card",
        "hy:lt-kicker-name",
        "hy:lt-mask-reveal",
        "hy:lt-side-rule",
        "hy:lt-soft-pill",
        "hy:lt-stack-bars",
    ],
    "pointer": [
        "hy:multiplayer-cursors",
        "hy:oversized-cursor",
        "hy:pull-to-refresh",
        "hy:touch-indicator",
    ],
    "pointers": [
        "hy:pull-to-refresh",
    ],
    "pop": [
        "hy:number-pop-in",
        "hy:spring-pop",
    ],
    "portrait": [
        "hy:caption-camera-follow",
        "hy:flowchart-vertical",
    ],
    "presence": [
        "hy:multiplayer-cursors",
    ],
    "presentation": [
        "hy:mk-background",
    ],
    "press": [
        "hy:press-ripple",
    ],
    "pressure": [
        "hy:overwhelm-surround",
    ],
    "problem": [
        "hy:decline-chart",
    ],
    "problem-setup": [
        "hy:radial-surround",
    ],
    "product-demo": [
        "hy:browser-device-stage",
        "hy:code-terminal-run",
        "hy:icon-morph-beat",
        "hy:native-notification-pop",
        "hy:notification-stack",
        "hy:offset-path-traveler",
        "hy:press-ripple",
        "hy:screen-flow-carousel",
        "hy:segmentation-flood",
        "hy:soft-blob-touch",
        "hy:spring-stack-shuffle",
        "hy:state-chip-rail",
        "hy:sticky-mock-swap",
        "hy:telemetry-hud",
        "hy:tracing-beam",
        "hy:typed-prompt",
        "hy:ui-focus-zoom",
    ],
    "professional": [
        "hy:mk-background",
        "hy:mk-specs-list",
    ],
    "progress": [
        "hy:chart-story",
        "hy:conic-progress-ring",
    ],
    "promotion": [
        "hy:heygen-avatar-promo-card",
    ],
    "prompt": [
        "hy:typed-prompt",
    ],
    "proof": [
        "hy:chart-story",
        "hy:count-up",
        "hy:outline-draw",
        "hy:testimonial-proof-card",
        "hy:trust-strip",
    ],
    "prop": [
        "hy:before-after-wipe",
        "hy:camera-scan-gate",
        "hy:comparison-split",
        "hy:device-frame-stage",
        "hy:store-badge-lockup",
        "hy:testimonial-card",
        "hy:toggle-flip",
        "hy:vector-editor-rig",
    ],
    "prove": [
        "hy:avatar-cloud",
        "hy:conic-progress-ring",
        "hy:logo-wall",
        "hy:multiplayer-cursors",
        "hy:star-rating-fill",
        "hy:testimonial-card",
    ],
    "pull-back": [
        "hy:pull-back-reveal",
    ],
    "pulse": [
        "hy:beat-pulse-background",
    ],
    "push-in": [
        "hy:push-in",
    ],
    "qr": [
        "hy:camera-scan-gate",
    ],
    "quantize": [
        "hy:ascii-render-pass",
        "hy:ordered-dither-pass",
    ],
    "quote": [
        "hy:testimonial-card",
        "hy:testimonial-proof-card",
    ],
    "radial": [
        "hy:radial-surround",
    ],
    "rail": [
        "hy:screen-flow-carousel",
        "hy:state-chip-rail",
        "hy:swipe-rail",
        "hy:velocity-throw-snap",
    ],
    "ranking": [
        "hy:bar-chart-race",
    ],
    "raster": [
        "hy:wordmark-tiles",
    ],
    "rating": [
        "hy:star-rating-fill",
    ],
    "reactive": [
        "hy:beat-pulse-background",
    ],
    "recognition": [
        "hy:camera-scan-gate",
    ],
    "recontextualize": [
        "hy:pull-back-reveal",
    ],
    "recording": [
        "hy:camcorder-hud",
    ],
    "reddit": [
        "hy:reddit-post",
    ],
    "refactor": [
        "hy:code-morph",
    ],
    "reference-prop": [
        "hy:toggle-flip",
    ],
    "refresh": [
        "hy:pull-to-refresh",
    ],
    "reshape": [
        "hy:morph-swap",
    ],
    "resistance": [
        "hy:rubber-band-bumper",
    ],
    "retro": [
        "hy:oscilloscope-trace",
    ],
    "reveal": [
        "hy:ascii-trail-reveal",
        "hy:bottom-up-letters",
        "hy:caption-clip-wipe",
        "hy:constellation-hub",
        "hy:grade-split-reveal",
        "hy:ink-bleed-reveal",
        "hy:kinetic-type-swap",
        "hy:locked-nucleus-orbit",
        "hy:logo-sting",
        "hy:panel-reveal",
        "hy:parallax-unzoom",
        "hy:particle-image-reveal",
        "hy:per-word-rise",
        "hy:pull-back-reveal",
        "hy:scramble-reveal",
        "hy:skeleton-reveal",
        "hy:soft-blur-in",
        "hy:split-flap-board",
        "hy:spring-pop",
        "hy:svg-mask-reveal",
        "hy:svg-stroke-trace",
        "hy:ticker-takeover",
        "hy:tracking-in",
        "hy:ui-3d-reveal",
        "hy:whiteboard-ink",
        "hy:wordmark-tiles",
    ],
    "rhythmic": [
        "hy:beat-pulse-background",
    ],
    "ring": [
        "hy:conic-progress-ring",
        "hy:radial-surround",
    ],
    "ripple": [
        "hy:press-ripple",
    ],
    "rubber-band": [
        "hy:rubber-band-bumper",
    ],
    "scan": [
        "hy:camera-scan-gate",
        "hy:scan-band",
    ],
    "scatter": [
        "hy:char-slam-explode",
    ],
    "scene": [
        "hy:fade-through",
    ],
    "scramble": [
        "hy:caption-matrix-decode",
        "hy:scramble-reveal",
    ],
    "scrapbook": [
        "hy:freeze-frame-dressing",
    ],
    "screens": [
        "hy:screen-flow-carousel",
    ],
    "scroll": [
        "hy:code-scroll",
        "hy:scroll-camera-story",
        "hy:scroll-feed",
    ],
    "sections": [
        "hy:scroll-camera-story",
    ],
    "separator": [
        "hy:separator",
    ],
    "sequencing": [
        "hy:beat-timeline",
    ],
    "servo": [
        "hy:scroll-camera-story",
        "hy:ui-focus-zoom",
    ],
    "settings": [
        "hy:settings-toggle-flow",
    ],
    "sfx": [
        "hy:apple-money-count",
        "hy:blue-sweater-intro-video",
        "hy:nyc-paris-flight",
        "hy:vpn-youtube-spot",
    ],
    "shader": [
        "hy:chromatic-radial-split",
        "hy:cinematic-zoom",
        "hy:code-shader-dissolve",
        "hy:cosmic-orb",
        "hy:cross-warp-morph",
        "hy:domain-warp-dissolve",
        "hy:flash-through-white",
        "hy:glitch",
        "hy:gravitational-lens",
        "hy:halftone-field",
        "hy:light-leak",
        "hy:rack-focus",
        "hy:ridged-burn",
        "hy:ripple-waves",
        "hy:sdf-iris",
        "hy:swirl-vortex",
        "hy:thermal-distortion",
        "hy:vfx-text-cursor",
        "hy:whip-pan",
    ],
    "shake": [
        "hy:camera-shake",
    ],
    "share-sheet": [
        "hy:share-sheet-carousel",
    ],
    "shared-element": [
        "hy:modal-morph",
    ],
    "sheet": [
        "hy:sheet-spring-up",
    ],
    "shimmer": [
        "hy:shimmer-sweep",
        "hy:text-shimmer",
    ],
    "showcase": [
        "hy:ai-chat-reveal",
        "hy:app-showcase",
        "hy:apple-money-count",
        "hy:blue-sweater-intro-video",
        "hy:chatgpt-exchange",
        "hy:claude-exchange",
        "hy:code-snippet-apple-terminal-basic",
        "hy:code-snippet-apple-terminal-clear-dark",
        "hy:code-snippet-apple-terminal-clear-light",
        "hy:code-snippet-apple-terminal-grass",
        "hy:code-snippet-apple-terminal-homebrew",
        "hy:code-snippet-apple-terminal-man-page",
        "hy:code-snippet-apple-terminal-novel",
        "hy:code-snippet-apple-terminal-ocean",
        "hy:code-snippet-apple-terminal-pro",
        "hy:code-snippet-apple-terminal-red-sands",
        "hy:code-snippet-apple-terminal-silver-aerogel",
        "hy:code-snippet-apple-terminal-solid-colors",
        "hy:code-snippet-dark-2026",
        "hy:code-snippet-dark-modern",
        "hy:code-snippet-dark-plus",
        "hy:code-snippet-high-contrast",
        "hy:code-snippet-high-contrast-light",
        "hy:code-snippet-light-2026",
        "hy:code-snippet-light-modern",
        "hy:code-snippet-light-plus",
        "hy:code-snippet-monokai",
        "hy:code-snippet-solarized-light",
        "hy:code-snippet-visual-studio-dark",
        "hy:code-snippet-visual-studio-light",
        "hy:cosmic-orb",
        "hy:gallery-tunnel",
        "hy:heygen-avatar-promo-card",
        "hy:message-thread-reveal",
        "hy:north-korea-locked-down",
        "hy:notes-reveal",
        "hy:notification-cascade",
        "hy:nyc-paris-flight",
        "hy:oscilloscope-trace",
        "hy:rack-focus",
        "hy:share-sheet-carousel",
        "hy:slack-notification-ad",
        "hy:transitions-3d",
        "hy:transitions-blur",
        "hy:transitions-cover",
        "hy:transitions-destruction",
        "hy:transitions-dissolve",
        "hy:transitions-distortion",
        "hy:transitions-grid",
        "hy:transitions-light",
        "hy:transitions-mechanical",
        "hy:transitions-other",
        "hy:transitions-push",
        "hy:transitions-radial",
        "hy:transitions-scale",
        "hy:ui-3d-reveal",
        "hy:vfx-anamorphic-flare",
        "hy:vpn-youtube-spot",
    ],
    "signup": [
        "hy:signup-flow",
    ],
    "skeleton": [
        "hy:skeleton-reveal",
    ],
    "slam": [
        "hy:caption-kinetic-slam",
        "hy:char-slam-explode",
        "hy:headline-slam",
    ],
    "slide": [
        "hy:page-slide",
        "hy:physical-exit",
    ],
    "slit-scan": [
        "hy:slit-scan-reveal",
    ],
    "slot": [
        "hy:browser-device-stage",
        "hy:screen-flow-carousel",
        "hy:scroll-camera-story",
        "hy:ui-focus-zoom",
        "hy:whiteboard-ink",
    ],
    "slot-machine": [
        "hy:ticker-takeover",
    ],
    "slots": [
        "hy:before-after-wipe",
        "hy:iris-reveal",
        "hy:light-sweep-pass",
        "hy:morph-swap",
        "hy:split-tilt-cards",
        "hy:whip-pan-cut",
    ],
    "snap": [
        "hy:velocity-throw-snap",
    ],
    "social": [
        "hy:caption-emoji-pop",
        "hy:caption-highlight",
        "hy:editorial-flash-overlay",
        "hy:freeze-frame-dressing",
        "hy:instagram-follow",
        "hy:macos-notification",
        "hy:reddit-post",
        "hy:spotify-card",
        "hy:thread-message-stack",
        "hy:tiktok-follow",
        "hy:x-post",
        "hy:yt-comment-card",
        "hy:yt-lower-third",
    ],
    "social-overlay": [
        "hy:x-follow-card",
    ],
    "social-proof": [
        "hy:avatar-cloud",
        "hy:logo-wall",
        "hy:social-proof-card",
        "hy:testimonial-card",
        "hy:testimonial-proof-card",
    ],
    "solari": [
        "hy:split-flap-board",
    ],
    "space": [
        "hy:spiral-galaxy",
    ],
    "spain": [
        "hy:spain-map",
    ],
    "specular": [
        "hy:text-shimmer",
    ],
    "speech-bubble": [
        "hy:hw-text-cloud",
    ],
    "speed-ramp": [
        "hy:whip-pan-cut",
    ],
    "splay": [
        "hy:multi-device-splay",
    ],
    "split-flap": [
        "hy:split-flap-board",
    ],
    "spotify": [
        "hy:spotify-card",
    ],
    "spotlight": [
        "hy:tracing-beam",
        "hy:yt-feather-highlight",
    ],
    "spring": [
        "hy:native-notification-pop",
        "hy:sheet-spring-up",
        "hy:spring-pop",
    ],
    "stack": [
        "hy:notification-stack",
        "hy:spring-stack-shuffle",
    ],
    "stage": [
        "hy:browser-device-stage",
    ],
    "stagger": [
        "hy:grid-card-assemble",
        "hy:logo-wall",
        "hy:notification-stack",
        "hy:per-word-rise",
        "hy:stagger-cascade",
        "hy:text-stagger",
    ],
    "stars": [
        "hy:star-rating-fill",
    ],
    "stat": [
        "hy:mk-progress-stat",
    ],
    "state-change": [
        "hy:icon-morph-beat",
    ],
    "state-machine": [
        "hy:state-chip-rail",
    ],
    "stations": [
        "hy:pan-stations",
    ],
    "statistics": [
        "hy:bar-chart-race",
        "hy:data-chart",
    ],
    "stats": [
        "hy:chart-story",
        "hy:count-up",
    ],
    "status": [
        "hy:state-chip-rail",
    ],
    "stepped": [
        "hy:stop-motion-cadence",
    ],
    "stepper": [
        "hy:onboarding-stepper-flow",
    ],
    "sticky": [
        "hy:sticky-mock-swap",
    ],
    "sting": [
        "hy:beat-accent",
        "hy:logo-sting",
    ],
    "stitch": [
        "hy:stitched-text-draw",
    ],
    "stop-motion": [
        "hy:stop-motion-cadence",
    ],
    "store-badges": [
        "hy:store-badge-lockup",
    ],
    "story": [
        "hy:scroll-camera-story",
    ],
    "stroke": [
        "hy:svg-stroke-trace",
    ],
    "structure": [
        "hy:modal-morph",
    ],
    "success": [
        "hy:success-check",
    ],
    "surround": [
        "hy:radial-surround",
    ],
    "svg": [
        "hy:facet-morph",
        "hy:svg-mask-reveal",
        "hy:svg-stroke-trace",
        "hy:whiteboard-ink",
    ],
    "svg-filter": [
        "hy:ink-bleed-reveal",
    ],
    "swap": [
        "hy:icon-swap",
        "hy:line-swap",
        "hy:morph-swap",
        "hy:text-state-swap",
    ],
    "sweep": [
        "hy:light-sweep-pass",
    ],
    "swipe": [
        "hy:swipe-rail",
    ],
    "tablet": [
        "hy:device-frame-stage",
        "hy:multi-device-splay",
    ],
    "tabs": [
        "hy:tabs-slide-indicator",
    ],
    "tahoe": [
        "hy:macos-tahoe-liquid-glass",
    ],
    "tap": [
        "hy:gesture-tap",
    ],
    "tech": [
        "hy:caption-glitch-rgb",
    ],
    "telemetry": [
        "hy:telemetry-hud",
    ],
    "terminal": [
        "hy:code-snippet-apple-terminal-basic",
        "hy:code-snippet-apple-terminal-clear-dark",
        "hy:code-snippet-apple-terminal-clear-light",
        "hy:code-snippet-apple-terminal-grass",
        "hy:code-snippet-apple-terminal-homebrew",
        "hy:code-snippet-apple-terminal-man-page",
        "hy:code-snippet-apple-terminal-novel",
        "hy:code-snippet-apple-terminal-ocean",
        "hy:code-snippet-apple-terminal-pro",
        "hy:code-snippet-apple-terminal-red-sands",
        "hy:code-snippet-apple-terminal-silver-aerogel",
        "hy:code-snippet-apple-terminal-solid-colors",
        "hy:code-terminal-run",
    ],
    "testimonial": [
        "hy:testimonial-card",
        "hy:testimonial-proof-card",
    ],
    "text": [
        "hy:bottom-up-letters",
        "hy:caption-blend-difference",
        "hy:inline-highlight",
        "hy:morph-text",
        "hy:shimmer-sweep",
        "hy:soft-blur-in",
        "hy:split-flap-board",
        "hy:text-stagger",
        "hy:text-state-swap",
        "hy:texture-mask-text",
        "hy:tracking-in",
        "hy:vfx-text-cursor",
        "hy:weight-wave",
    ],
    "text-effect": [
        "hy:blur-in",
        "hy:caption-blend-difference",
        "hy:morph-text",
        "hy:streaming-text",
        "hy:texture-mask-text",
    ],
    "text-effects": [
        "hy:kinetic-type-swap",
        "hy:line-swap",
        "hy:particle-text-dissolve",
        "hy:per-word-rise",
        "hy:scramble-reveal",
        "hy:text-shimmer",
    ],
    "text-treatment": [
        "hy:char-slam-explode",
        "hy:hw-underline",
        "hy:mk-emphasis-type",
    ],
    "texture": [
        "hy:ascii-render-pass",
        "hy:caption-texture",
        "hy:grain-field",
        "hy:grain-overlay",
        "hy:halftone-dissolve",
        "hy:halftone-field",
        "hy:ink-bleed-reveal",
        "hy:ordered-dither-pass",
        "hy:texture-mask-text",
        "hy:yt-lcd-background",
        "hy:yt-screen-warp",
    ],
    "three-js": [
        "hy:three-orbiting-cards",
    ],
    "throw": [
        "hy:velocity-throw-snap",
    ],
    "ticker": [
        "hy:news-ticker",
        "hy:ticker-takeover",
    ],
    "tiktok": [
        "hy:caption-highlight",
        "hy:tiktok-follow",
    ],
    "tilegrid": [
        "hy:us-map-hex",
    ],
    "tiles": [
        "hy:wordmark-tiles",
    ],
    "tilt": [
        "hy:split-tilt-cards",
        "hy:tilt-card",
    ],
    "time": [
        "hy:slit-scan-reveal",
    ],
    "time-law": [
        "hy:stop-motion-cadence",
    ],
    "timeline": [
        "hy:beat-timeline",
    ],
    "title": [
        "hy:weight-wave",
    ],
    "title-card": [
        "hy:hw-title",
        "hy:titlecard-calm",
        "hy:titlecard-lockup",
        "hy:yt-prism-title",
    ],
    "toggle": [
        "hy:settings-toggle-flow",
        "hy:toggle-flip",
    ],
    "toss": [
        "hy:physical-exit",
    ],
    "touch": [
        "hy:soft-blob-touch",
        "hy:touch-indicator",
    ],
    "trail": [
        "hy:ascii-trail-reveal",
        "hy:cursor-glyph-trail",
        "hy:echo-trail",
    ],
    "transition": [
        "hy:beat-freeze-cut",
        "hy:chromatic-radial-split",
        "hy:cinematic-zoom",
        "hy:cross-warp-morph",
        "hy:cut-the-curve",
        "hy:domain-warp-dissolve",
        "hy:editorial-flash-overlay",
        "hy:fade-through",
        "hy:flash-through-white",
        "hy:glitch",
        "hy:gravitational-lens",
        "hy:grid-pixelate-wipe",
        "hy:halftone-dissolve",
        "hy:hw-scribble-transition",
        "hy:iris-reveal",
        "hy:light-leak",
        "hy:match-cut",
        "hy:micro-transitions",
        "hy:mk-clone-wall-transition",
        "hy:morph-swap",
        "hy:ordered-dither-pass",
        "hy:organic-light-leak-overlay",
        "hy:parallax-device-dive",
        "hy:parallax-unzoom",
        "hy:parallax-zoom",
        "hy:ridged-burn",
        "hy:ripple-waves",
        "hy:rubber-band-bumper",
        "hy:sdf-iris",
        "hy:swirl-vortex",
        "hy:thermal-distortion",
        "hy:transitions-3d",
        "hy:transitions-blur",
        "hy:transitions-cover",
        "hy:transitions-destruction",
        "hy:transitions-dissolve",
        "hy:transitions-distortion",
        "hy:transitions-grid",
        "hy:transitions-light",
        "hy:transitions-mechanical",
        "hy:transitions-other",
        "hy:transitions-push",
        "hy:transitions-radial",
        "hy:transitions-scale",
        "hy:type-match-cut",
        "hy:whip-pan",
        "hy:whip-pan-cut",
    ],
    "transition-primitive": [
        "hy:avatar-group-hover",
        "hy:badge-pop",
        "hy:card-resize",
        "hy:chromatic-aberration-wipe",
        "hy:directional-wipe",
        "hy:icon-swap",
        "hy:input-feedback",
        "hy:menu-morph",
        "hy:micro-transitions",
        "hy:number-pop-in",
        "hy:page-slide",
        "hy:panel-reveal",
        "hy:skeleton-reveal",
        "hy:success-check",
        "hy:tabs-slide-indicator",
        "hy:text-stagger",
        "hy:text-state-swap",
        "hy:tilt-card",
        "hy:zoom-through-transition",
    ],
    "transitions": [
        "hy:beat-timeline",
    ],
    "transitions-dev-port": [
        "hy:avatar-group-hover",
        "hy:badge-pop",
        "hy:card-resize",
        "hy:icon-swap",
        "hy:input-feedback",
        "hy:menu-morph",
        "hy:micro-transitions",
        "hy:number-pop-in",
        "hy:page-slide",
        "hy:panel-reveal",
        "hy:skeleton-reveal",
        "hy:success-check",
        "hy:tabs-slide-indicator",
        "hy:text-stagger",
        "hy:text-state-swap",
        "hy:tilt-card",
    ],
    "travel": [
        "hy:nyc-paris-flight",
    ],
    "traveler": [
        "hy:offset-path-traveler",
    ],
    "trust": [
        "hy:trust-strip",
    ],
    "twitter": [
        "hy:x-post",
    ],
    "type": [
        "hy:stitched-text-draw",
        "hy:variable-font-flex",
    ],
    "typing": [
        "hy:code-terminal-run",
        "hy:code-typing",
        "hy:notes-reveal",
        "hy:notes-typing",
        "hy:typed-prompt",
    ],
    "typography": [
        "hy:blur-out-up",
        "hy:caption-camera-follow",
        "hy:caption-editorial-emphasis",
        "hy:caption-kinetic-slam",
        "hy:caption-weight-shift",
        "hy:char-slam-explode",
        "hy:focus-blur-resolve",
        "hy:headline-slam",
        "hy:hw-path-text",
        "hy:hw-title",
        "hy:line-by-line-slide",
        "hy:logo-brand-close",
        "hy:marker-highlight",
        "hy:matrix-decode",
        "hy:mk-callout-highlight",
        "hy:mk-clone-wall-transition",
        "hy:mk-emphasis-type",
        "hy:morph-text",
        "hy:per-word-crossfade",
        "hy:per-word-rise",
        "hy:perspective-marquee",
        "hy:rgb-glitch-text",
        "hy:scan-band",
        "hy:shared-axis-y",
        "hy:shared-axis-z",
        "hy:slot-machine-roll",
        "hy:staggered-fade-up",
        "hy:strikethrough-replace",
        "hy:ticker-takeover",
        "hy:titlecard-calm",
        "hy:titlecard-lockup",
        "hy:top-down-letters",
        "hy:tracking-in",
        "hy:type-match-cut",
        "hy:typewriter",
        "hy:variable-axis-type",
        "hy:vox-annotate",
        "hy:weight-wave",
        "hy:wordmark-tiles",
        "hy:yt-prism-title",
    ],
    "ui": [
        "hy:dynamic-grid",
        "hy:micro-transitions",
        "hy:simulated-cursor",
    ],
    "ui-flow": [
        "hy:checkout-flow",
        "hy:onboarding-stepper-flow",
        "hy:settings-toggle-flow",
        "hy:signup-flow",
    ],
    "ui-props": [
        "hy:before-after-wipe",
        "hy:camera-scan-gate",
        "hy:comparison-split",
        "hy:cta-close",
        "hy:cta-lockup",
        "hy:device-frame-stage",
        "hy:focus-swap",
        "hy:gesture-tap",
        "hy:notification-pileup",
        "hy:store-badge-lockup",
        "hy:testimonial-card",
        "hy:toggle-flip",
        "hy:vector-editor-rig",
    ],
    "unzoom": [
        "hy:parallax-unzoom",
    ],
    "usa": [
        "hy:us-map",
        "hy:us-map-bubble",
        "hy:us-map-flow",
        "hy:us-map-hex",
    ],
    "variable-font": [
        "hy:variable-axis-type",
        "hy:variable-font-flex",
        "hy:weight-wave",
    ],
    "vector": [
        "hy:vector-editor-rig",
    ],
    "velocity": [
        "hy:motion-blur",
        "hy:velocity-throw-snap",
    ],
    "velocity-match": [
        "hy:cut-the-curve",
        "hy:whip-pan-cut",
    ],
    "vertical": [
        "hy:ai-chat-reveal",
        "hy:chat-thread",
        "hy:chatgpt-exchange",
        "hy:claude-exchange",
        "hy:heygen-avatar-promo-card",
        "hy:message-thread-reveal",
        "hy:notes-reveal",
        "hy:notes-typing",
        "hy:notification-cascade",
        "hy:share-sheet-carousel",
        "hy:slack-notification-ad",
        "hy:social-proof-card",
        "hy:yt-vertical-fill",
    ],
    "vfx": [
        "hy:vfx-anamorphic-flare",
    ],
    "video-primitive": [
        "hy:arc-motion-path",
        "hy:avatar-group-hover",
        "hy:badge-pop",
        "hy:blur-in",
        "hy:card-resize",
        "hy:chat-message",
        "hy:chromatic-aberration-wipe",
        "hy:dynamic-grid",
        "hy:icon-swap",
        "hy:lt-neon-border",
        "hy:menu-morph",
        "hy:number-pop-in",
        "hy:number-wheel",
        "hy:page-slide",
        "hy:separator",
        "hy:sheet-spring-up",
        "hy:simulated-cursor",
        "hy:skeleton-reveal",
        "hy:slot-machine-roll",
        "hy:staggered-fade-up",
        "hy:streaming-text",
        "hy:success-check",
        "hy:svg-line-draw-loader",
        "hy:text-stagger",
        "hy:text-state-swap",
        "hy:three-orbiting-cards",
        "hy:tilt-card",
        "hy:top-down-letters",
        "hy:typewriter",
        "hy:typing-indicator",
    ],
    "vignette": [
        "hy:vignette",
    ],
    "vscode": [
        "hy:code-snippet-dark-2026",
        "hy:code-snippet-dark-modern",
        "hy:code-snippet-dark-plus",
        "hy:code-snippet-high-contrast",
        "hy:code-snippet-high-contrast-light",
        "hy:code-snippet-light-2026",
        "hy:code-snippet-light-modern",
        "hy:code-snippet-light-plus",
        "hy:code-snippet-monokai",
        "hy:code-snippet-solarized-light",
        "hy:code-snippet-visual-studio-dark",
        "hy:code-snippet-visual-studio-light",
    ],
    "walkthrough": [
        "hy:simulated-cursor",
    ],
    "webgl": [
        "hy:code-3d-extrude",
        "hy:code-particle-assemble",
        "hy:code-shader-dissolve",
        "hy:cosmic-orb",
        "hy:gallery-tunnel",
        "hy:halftone-field",
        "hy:rack-focus",
        "hy:spiral-galaxy",
        "hy:three-orbiting-cards",
        "hy:vfx-liquid-background",
        "hy:vfx-liquid-glass",
        "hy:vfx-magnetic",
        "hy:vfx-portal",
        "hy:vfx-shatter",
    ],
    "webgpu": [
        "hy:ios26-liquid-glass",
        "hy:liquid-glass-context-menu",
        "hy:liquid-glass-media-controls",
        "hy:liquid-glass-notification",
        "hy:liquid-glass-widgets",
    ],
    "whip": [
        "hy:cut-the-curve",
    ],
    "whip-pan": [
        "hy:whip-pan-cut",
    ],
    "whiteboard": [
        "hy:whiteboard-ink",
    ],
    "wipe": [
        "hy:before-after-wipe",
        "hy:caption-clip-wipe",
        "hy:comparison-split",
        "hy:grid-pixelate-wipe",
        "hy:hw-scribble-transition",
        "hy:mk-clone-wall-transition",
    ],
    "word-swap": [
        "hy:kinetic-type-swap",
    ],
    "wordmark": [
        "hy:scan-band",
        "hy:svg-mask-reveal",
        "hy:wordmark-tiles",
    ],
    "wordmarks": [
        "hy:trust-strip",
    ],
    "world": [
        "hy:world-map",
    ],
    "youtube": [
        "hy:apple-money-count",
        "hy:north-korea-locked-down",
        "hy:nyc-paris-flight",
        "hy:vpn-youtube-spot",
        "hy:yt-lower-third",
    ],
    "zoom": [
        "hy:parallax-zoom",
        "hy:ui-focus-zoom",
        "hy:yt-camera-move",
    ],
}

def registry_templates_by_tag(tag: str) -> list[str]:
    return _TAG_TO_TEMPLATES.get(tag, [])

def is_hyperframes_registry_template(template_id: str) -> bool:
    return template_id in HYPERFRAMES_REGISTRY_TEMPLATES
